### ISSUE TITLE
Nothing is displaying after entering the value in search field

### ISSUE THREAD

**Issue by Amolnigdikar** [hackstarsj/Android_Auto_Complete_Location#1]

**Comment by hackstarsj** [comment]
Did you added your api key?

**Comment by Amolnigdikar** [comment]
yes I have added sir

**Comment by Amolnigdikar** [comment]
Is it necessary to link the billing account?

**Comment by hackstarsj** [comment]
Can u come in remote connection like TeamViewer?

**Comment by Amolnigdikar** [comment]
{
   "error_message" : "This IP, site or mobile application is not authorized to use this API key. Request received from IP address 183.87.117.91, with empty referer",
   "predictions" : [],
   "status" : "REQUEST_DENIED"
}

**Comment by Amolnigdikar** [comment]
This error is displaying in the browser after hitting the request with key

**Comment by hackstarsj** [comment]
I think you not enable location check my video tutorial for how to enable
api for location

**Comment by Amolnigdikar** [comment]
K sir thanks

**Comment by Amolnigdikar** [comment]
It's working sir thank you
